title: Bugmark
email: andy@r210.com
description: "Bugmark Information"
baseurl:  # the subpath of your site, e.g. /blog
url: https://bugmark.net
enforce_ssl: eastonlee.com
twitter_username: easton042
github_username:  easton042
linkedin_username:  eastonlee

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

safe: false

# easton
permalink: /blog/:year/:month/:day/:title/

# minima theme, deprecated
show_downloads: false
google_analytics: UA-58961104-2

tagline: experientialism
paginate:            1
sass:
  sass_dir:         _sass
  style:            :compressed
author: Bugmark 

analytics_id: UA-58961104-2

disqus:
  shortname: eastonlee

excerpt_separator: <!--more-->
