title: Bugmark
dev_email: andy@r210.com
email: getbugmark@gmail.com
description: "Bugmark Information"
url: https://bugmark.net
twitter_username: getbugmark
github_username:  bugmark

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

safe: false

permalink: /blog/:year/:month/:day/:title/

show_downloads: false
google_analytics: TBD

tagline: Software Issue Marketplace
paginate:            1
sass:
  sass_dir:         _sass
  style:            :compressed
author: Bugmark 

analytics_id: TBD

disqus:
  shortname: TBD

excerpt_separator: <!--more-->
